### ISSUE TITLE
Interaction with Proxy

### ISSUE THREAD

**Issue by pabloalmunia** [tc39/proposal-record-tuple#111]
How to work this kind of elements and Proxy? Can we to create a Proxy instance over a record o a tuple?

Congratulation, it is a very good proposal.

**Comment by ljharb** [comment]
Proxy only works on an object, so I'd expect it to not be able to target the primitive form.

**Comment by pabloalmunia** [comment]
Thanks, the nature of this type of data is clearer to me. The prototype in record and especially in tuple is little bit confuse if this kind of elements are primitives and are not a objects. 

Perhaps we can create a proxy over the Tuple and Record wrapper.

**Comment by ljharb** [comment]
You certainly could; just like how `Symbol()` is a primitive, not proxyable, but `Object(Symbol())` is an object that's proxyable.

**Comment by littledan** [comment]
I agree with @ljharb here; you can only Proxy objects. The wrapper for Records and Tuples will be an object, and work fine as a Proxy target. Do you have any specific questions or concerns about the interaction?

**Comment by pabloalmunia** [comment]
@littledan I am now clearer about the nature of these types of data. They are native immutable types and not objects, even though they have a prototype and look like objects (or arrays). Proxy interactions are a good test of their nature and behaviour.

**Comment by littledan** [comment]
(Note, Records and Tuples have a prototype to the same extent as Numbers do--their wrappers do, but the primitive doesn't.)

**Comment by pabloalmunia** [comment]
Well, it's true, but the wrappers is instrisictly called with I write some as `"hola".__proto__` or in a better mode: `Object.getPrototypeOf("hola")`.

As a result, can I write `Object.getPrototypeOf( #{} )`?

**Comment by rickbutton** [comment]
> As a result, can I write `Object.getPrototypeOf( #{} )`?

Yes, because `Object.getPrototypeOf` calls `ToObject`, so primitives passed to it will be boxed into their object counterparts: https://tc39.es/ecma262/#sec-object.getprototypeof

for example:
```js
Object.getPrototypeOf(1) === Number.prototype // true
```

**Comment by Jack-Works** [comment]
should we add invariants to the Proxy of boxed record/tuple that behaves like an immutable object?

```ts
p = new Proxy(Object(#{a: 1}), {
    get() { return 2 }
})
p.a
```
throws: Uncaught TypeError: 'get' on proxy: property 'a' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '1' but got '2')

**Comment by ljharb** [comment]
You can’t have a Proxy to a primitive.
