### ISSUE TITLE
Problem statement

### ISSUE THREAD

**Issue by dalssoft** [tc39/proposal-record-tuple#129]
I'm not sure this is the right channel but reading the proposal I couldn't find what problem(s) record/tuple (or immutability) are trying to solve.

It would be great to have these statements at the beginning of the proposal

**Comment by rricard** [comment]
Hi @dalssoft, thank you for bringing that up, it is indeed not evident to see why people would need such proposal if they did not have prior experiences with immutable data structures in either JS or other languages. I'm [proposing adding it to the FAQ](https://github.com/tc39/proposal-record-tuple/issues/60#issuecomment-638752254) as the introduction is already quite long and if you are already familiar with those kind of structures, it would not be useful.

> Fully agree, i think some "state in ....(some state manager) not immutable" problem to solve. I hope someone will stop to hype way and drop fully any state manager from his code

We are not prescribing any use for this proposal, people should feel free to use them for anything and that includes state management solutions but not necessarily: immutable data structures provide strong guarantees that are useful in lots of places.

I'm going to close that issue as it is tracked in the FAQ issue now.
