### ISSUE TITLE
Example indicates object strict equality?

### ISSUE THREAD

**Issue by rwaldron** [tc39/proposal-record-tuple#17]
Does the `const` somehow change the way === works?

```Js   
assert(updatedData === const [
    { ticker: "AAPL", lastPrice: 195.891 },
    { ticker: "SPY", lastPrice: 286.61 },
]);
```

**Comment by isiahmeadows** [comment]
The way I was reading the proposal, it's value equality like strings and bigints, not identity like standard objects. So I believe that's the implication, but in a similar way bigints changed strict equality.

**Comment by mheiber** [comment]
The examples here might help: https://github.com/rricard/proposal-const-value-types#examples

If that makes the semantics of const objects with `===` clear, can we close this issue?

**Comment by mheiber** [comment]
ping @rwaldron to see if we can close this issue ^ https://github.com/rricard/proposal-const-value-types/issues/17#issuecomment-521200473

**Comment by rricard** [comment]
This issue is stale now. Closing, please ping if you want to reopen it.
