### ISSUE TITLE
Record as React prop playground bug

### ISSUE THREAD

**Issue by slorber** [tc39/proposal-record-tuple#195]
Hey all

Just reporting that I had this issue in the playground:

---

This does not work:

https://rickbutton.github.io/record-tuple-playground/#eyJjb250ZW50IjoiaW1wb3J0IFJlYWN0IGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdFwiO1xuaW1wb3J0IFJlYWN0RE9NIGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdC1kb21cIjtcblxuXG5jb25zdCBIZWxsbyA9ICh7dXNlcn0pID0+IHtcbiAgcmV0dXJuIDxwPkhlbGxvIHt1c2VyLm5hbWV9PC9wPlxufTtcblxuUmVhY3RET00ucmVuZGVyKFxuICAgIDxIZWxsbyB1c2VyPXsje25hbWU6IFwiU2ViYXN0aWVuXCJ9fS8+LFxuICAgIGRvY3VtZW50LmJvZHksXG4pO1xuXG4iLCJzeW50YXgiOiJoYXNoIiwiZG9tTW9kZSI6dHJ1ZX0=

```jsx
const Hello = ({user}) => {
  return <p>Hello {user.name}</p>
};

ReactDOM.render(
    <Hello user={#{name: "Sebastien"}}/>,
    document.body,
);
```

---

But this does:

https://rickbutton.github.io/record-tuple-playground/#eyJjb250ZW50IjoiaW1wb3J0IFJlYWN0IGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdFwiO1xuaW1wb3J0IFJlYWN0RE9NIGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdC1kb21cIjtcblxuXG5jb25zdCBIZWxsbyA9ICh7dXNlcn0pID0+IHtcbiAgcmV0dXJuIDxwPkhlbGxvIHt1c2VyLm5hbWV9PC9wPlxufTtcblxuY29uc3QgdXNlciA9ICN7bmFtZTogXCJTZWJhc3RpZW5cIn1cblxuUmVhY3RET00ucmVuZGVyKFxuICAgIDxIZWxsbyB1c2VyPXt1c2VyfS8+LFxuICAgIGRvY3VtZW50LmJvZHksXG4pO1xuXG4iLCJzeW50YXgiOiJoYXNoIiwiZG9tTW9kZSI6dHJ1ZX0=

```jsx
const Hello = ({user}) => {
  return <p>Hello {user.name}</p>
};

const user = #{name: "Sebastien"}

ReactDOM.render(
    <Hello user={user}/>,
    document.body,
);
```

![image](https://user-images.githubusercontent.com/749374/89665808-8b03b400-d8d9-11ea-9b80-801b3ddf1bb9.png)

---

BTW not sure what's the best place to report such playground bugs.

I found the playground repo, but it is quite hard to find, so I supposed this was the better place to report?

**Comment by nicolo-ribaudo** [comment]
This is a parser bug, could you reopen it in https://github.com/babel/babel? 🙏
