### ISSUE TITLE
Handling of symbol keys when creating a record

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/proposal-record-tuple#237]
Currently records cannot contain symbol keys. We handle it in two different ways, when using the `Record()` constructor and when using the records syntax:
1. `#{ [Symbol()]: 1 }` -> TypeError
2. `#{ ...{ [Symbol()]: 1 } }` -> TypeError
3. `Record({ [Symbol()]: 1 })` -> `#{}` (the symbol is ignored)

(1) makes sense, but probably (2) and (3) should be aligned: either we always collect symbols from the object used to define the record properties, or we always ignore them even if they are enumerable.

**Comment by rricard** [comment]
Agreement on having 3 throw.
