### ISSUE TITLE
Spec description of Box typo

### ISSUE THREAD

**Issue by acutmore** [tc39/proposal-record-tuple#255]
- [x] My issue is not a duplicate
- [x] My issue relates to the Records and Tuples proposal and not a [follow-on proposal](https://github.com/tc39/proposal-record-tuple#are-there-any-follow-up-proposals-being-considered)

It looks like there was a copy-paste error as the Box description sounds like it is talking about Tuples.

> A Box object is an exotic object that encapsuates a Box value and exposes virtual integer-indexed data properties corresponding to the individual entries set on the underlying Box value

https://github.com/tc39/proposal-record-tuple/blob/a5300795b3ab415c0cbdb355ae47e3489c900c42/spec/ordinary-and-exotic-object-behaviours.html#L381

There is also a small typo: 'encapsuates' -> 'encapsulates'

**Comment by rricard** [comment]
It is most likely a copy-paste error

**Comment by nicolo-ribaudo** [comment]
Bye bye boxes.
