### ISSUE TITLE
Unused variable in spec for tuple.prototype.slice()

### ISSUE THREAD

**Issue by catamorphism** [tc39/proposal-record-tuple#261]
In https://tc39.es/proposal-record-tuple/#sec-tuple.prototype.slice , step 9, variable _n_ is initialized to 0. The loop in step 10 increments _n_, but the value of _n_ is never used. I'm not sure what was intended.

**Comment by nicolo-ribaudo** [comment]
Good catch! `n` is indeed unnecessary. It was copied over from the Array method, where it was need to set the n-th property (for tuples, we just "append" the new element to the list).
