### ISSUE TITLE
Box, interact with ShadowRealm

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-record-tuple#267]
What will happen?

```ts
a = Box(() => {})

const f = newRealm.eval(`a => Box.deref(a)`)
```

What will happen? Is it going to be dereferenced as a `Wrapped Function Exotic Object`?

**Comment by nicolo-ribaudo** [comment]
We removed boxes from the proposal, since it was stalled because of them. I'm closing this issue, but we'll keep track of it if we'll bring them up again as a follow on proposal.
