### ISSUE TITLE
It is better to use `{|...|}` and `[|....|]`

### ISSUE THREAD

**Issue by xp44mm** [tc39/proposal-record-tuple#287]
It is better to use `{|...|}` and `[|....|]`. The former represents records and the latter tuples. Two bars represent a stub that makes mutable objects and arrays immutable. And this form makes the opening tag and the closing tag more symmetrical. And prefix `#` not like a function call. prefix look like a comment in some lang. or private member name in js.

```js
# {...}
record({...})
{|...|}

# [...]
tuple([...])
[|...|]
```

**Comment by rricard** [comment]
#10 already discusses syntax options.

We are not considering this syntax anymore (it was seriously considered at some point) as it has been discussed in #10 and rejected. We are still considering the `{| }` / `[| ]` at the moment.
