### ISSUE TITLE
ToPrimitive of Record wrapper throws

### ISSUE THREAD

**Issue by acutmore** [tc39/proposal-record-tuple#320]
[ToPrimitive](https://tc39.es/ecma262/#sec-toprimitive) of an object relies on looking up methods on the value, there is no default behavior:

```js
delete Symbol.prototpe.toString;
delete Symbol.prototpe.valueOf;
delete Symbol.prototpe[Symbol.toPrimtive];
Object.setPrototypeOf(Symbol.prototype, null);

Symbol() == Object(Symbol()); // throws
```

This behavior currently happens by default for Record wrappers because they have a null prototype.

```js
#{} == Object(#{}) // throws
```

It seems more future-proof to allow Record wrappers to safely pass `ToPrimitive` by unwrapping to their record primitive content. `ToString` and `ToNumber` can still throw.

We could add support for this either by adding a direct case for handing records to `ToPrimitive`, or always add a non-enumerable `Symbol.toPrimitive` to Record wrappers - though this would add a new hidden intrinsic.

**Comment by ljharb** [comment]
tbh I would prefer both.
