### ISSUE TITLE
Ensure correct behavior of Tuple methods that refer to the definition of Array methods

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/proposal-record-tuple#323]
Some of the tuple methods, such as [Tuple.prototype.map](https://tc39.es/proposal-record-tuple/#sec-tuple.prototype.map), are defined with explicit steps and, when they have a callback, they pass the result of `thisTupleValue(this)` as the last parameter.
Other tuple methods, such as [Tuple.prototype.forEach](https://tc39.es/proposal-record-tuple/#sec-tuple.prototype.foreach), are defined as a diff from the relative Array method, with references to `this` replaced with `thisTupleVaue(this)`. However, array methods call `ToObject(this)` (which thus ends up being `ToObject(thisTupleVaue(this)))`) and pass the resulting object as the last parameter to the callback function.

In practice, this means that `#[1].forEach((v, i, tup) => console.log(typeof tup))` logs `"object"` instead of `"tuple"`: we should fix how we define those methods to make sure that the last parameter is correctly a primitive tuple.

Ref https://github.com/tc39/proposal-record-tuple/pull/317#discussion_r920270217

**Comment by ljharb** [comment]
I think the longer term approach is to actually have explicit spec steps instead of the indirect "x, but replace step y with z" approach.
