### ISSUE TITLE
Naming JSON.parsePrimitive instead of parseImmutable 

### ISSUE THREAD

**Issue by hax** [tc39/proposal-record-tuple#327]
I think "immutable" is more broad, it could also mean immutable objects, people may think `JSON.parseImmutable` returns deep frozen immutable array/objects. So `parsePrimitive` may be the more accurate name.

Another reason that I don't like "immutable" in the API name, is it make us impossible to explore the possibility of "mutable" value type (like Swift, Kotlin) in the future.

**Comment by rricard** [comment]
That sounds like we'll be able to discuss this in the detached proposal for `parseImmutable` that we intend to detach in #330.
