### ISSUE TITLE
Removal of `Record.isRecord` & `Tuple.isTuple`

### ISSUE THREAD

**Issue by rricard** [tc39/proposal-record-tuple#335]
Per #333 - `Record.isRecord` & `Tuple.isTuple` should not be checking for wrappers as discussed in plenary.

They are now equivalent as using `typeof` so they are not useful anymore: we should probably remove them.

**Comment by ljharb** [comment]
While this is fine, do note that because it requires try/catch (which the predicate doesn’t) this necessitates a userland abstraction/package which wasn’t previously necessary.
