### ISSUE TITLE
Does `.with()` accept array as first argument?

### ISSUE THREAD

**Issue by llllvvuu** [tc39/proposal-record-tuple#382]
This would be [similar to Immutable.js 's `setIn`](https://immutable-js.com/docs/v4.3.0/setIn()/).

If this is the case already, should we document it?

**Comment by acutmore** [comment]
Hi @llllvvuu , `Tuple.protoype.with` is a cousin of `Array.prototype.with`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/with, so the first argument is the integer index.
