### ISSUE TITLE
examples of non-assignment/update member expression operations?

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-record-tuple#40]
All the examples in the readme are with updates, I assume:

```mjs
let a = #{x: 1};
assert(a.x === 1);
let b = #[2];
assert(b[0] === 2);
```

Are the expected syntax for reading fields in this manner and is intended to work.

**Comment by ljharb** [comment]
I would thus also assume that optional chaining, and bracket access, worked as expected.

**Comment by rickbutton** [comment]
yep @bmeck they would work as you have described. I should add a couple of examples describing it to the examples section.

@ljharb I agree, they would behave as expected. I should also add a blurb about those in-flight proposals and how they interact with const value types.

**Comment by mheiber** [comment]
I'd be happy to review a PR for adding these examples and links to related proposals.
