### ISSUE TITLE
Tuples across Realms

### ISSUE THREAD

**Issue by tolmasky** [tc39/proposal-record-tuple#47]
[Here](https://github.com/rricard/proposal-const-value-types#tuple-prototype) it mentions that "the Tuple prototype is an object that contains the same methods as Array with a few changes". This could lead to some problems when dealing with tuples across realms. Namely, it's possible to have two tuples that are "identical" but their prototypes are not (in the same way that `Object.getPrototypeOf(arrayFromRealmA) !== Object.getPrototypeOf(arrayFromRealmB))`. This can be of particular importance if we expect these prototypes to really be "just objects", where one could modify them, leading to a situation where the prototypes are in fact quite different across different realms beyond merely not being "value identical". You can imagine someone removing `.pop` for example, and arguably this is an interesting question even in the non-multi-realm case.

So, a couple options:

1. One could argue that perhaps that prototypes of tuples should be `Records` themselves, ensuring that they can't be modified and avoiding a whole class of weird errors normal objects have, while allowing tuples from different realms to be trivially comparable. Of course, the main problem with this is that `Records` under the current spec do not allow storing functions, since functions aren't value types. It would be interesting to allow function value types (functions that do not reference anything outside their scope, aka supercombinators, and that effectively act as frozen -- the built-ins like pop would have native implementations so they would not have to be strangely written).

2. Maybe tuples shouldn't have prototype methods at all, and we can simply provide "utility" functions to use with them, like `pop(tuple)`. With the "::" syntax, we could also have almost the same usage: `tuple::pop()`

3. The tuple prototype is some sort of super magic object that is both frozen and identical across realms (preferably not this).

**Comment by ljharb** [comment]
If they're primitives, then like other primitives, they'd always adopt the [[Prototype]] from the current realm.

**Comment by littledan** [comment]
I agree with @ljharb 's answer, but I'd like to see an explanation of this explicitly in the explainer, since it's not obvious to many readers.
