### ISSUE TITLE
What are the advantages over Object.freeze / deepFreeze

### ISSUE THREAD

**Issue by GrosSacASac** [tc39/proposal-record-tuple#83]
The advantages are unclear after reading the readme.

**Comment by mweststrate** [comment]
Make sure to grok this section:
https://github.com/tc39/proposal-record-tuple#equality. A vary fundamental
difference is that cannot be achieved in current JavaScript is that tuples
and records are value types, not reference types. Two frozen different
objects with the same contents are not necessarily the same thing (they
just look alike). Two records with the same contents are guaranteed to have
the same identity.

**Comment by GrosSacASac** [comment]
Why is that an advantage ? Just to make `===` work or something else ?

I am thinking about making another proposal which adds deepFreeze and deepEqual in std.

**Comment by mweststrate** [comment]
That is quite an important advantage for many abstractions and libraries.
And unlike deepEqual, it has predictable performance :)

**Comment by rickbutton** [comment]
The proposal mentions [several possible optimizations](https://github.com/tc39/proposal-record-tuple#what-are-the-performance-expectations-of-those-data-structures) that `Object.freeze` (or an implementation of `Object.deepFreeze`) can't provide.

**Comment by littledan** [comment]
Note that it's not clear if we can provide *predictable* performance, but it seems a lot more optimizable. I think we should be able to do the union of optimizations for normal JS objects and also for immutable data structure libraries.

**Comment by dcporter** [comment]
> Note that it's not clear if we can provide predictable performance

(Is there a discussion of this somewhere else? My uninformed gut feel is that it's very predictable, based on the record/tuple's shallow size.)

**Comment by littledan** [comment]
Well, we plan to do more investigation on performance properties during Stage 2, once we get the basic semantics figured out. For now, you can refer to the README.

**Comment by rricard** [comment]
Advantages should be covered in README, we already have an another issue (#2) to look at performance. Will close for now, feel free to ping here to ask to reopen if you feel we did not answer correctly.
